version: 1
accounts:
  - name: alice
    coins:
      - 20000000000000garden
  - name: bob
    coins:
      - 10000000000000garden
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5token
    - 10000000000garden
validators:
  - name: alice
    bonded: 1000000garden
genesis:
  chain_id: "cosmos:smpl-identity-chain"
  app_state:
    staking:
      params:
        bond_denom: "garden"
    crisis:
      constant_fee:
        denom: garden
    mint:
      minter:
        inflation: "0.0"
      params:
        mint_denom: garden
        inflation_max: "0.0"
        inflation_min: "0.0"
        inflation_rate_change: "0.0"
    bank:
      denom_metadata:
        - description: "Stable token"
          name: "smplst"
          symbol: "smplst"
          display: "smplst"
          base: "bsmplst"
          denom_units:
            - denom: "bsmplst"
              exponent: 0
            - denom: "smplst"
              exponent: 6
        - description: "Pegged USD token"
          name: "usdse"
          symbol: "usdse"
          display: "usdse"
          base: "busdse"
          denom_units:
            - denom: "busdse"
              exponent: 0
            - denom: "usdse"
              exponent: 6
        - description: "SMPL token"
          name: "SMPL"
          symbol: "smpl"
          display: "smpl"
          base: "garden"
          denom_units:
            - denom: "garden"
              exponent: 0
              aliases:
                - "bsmpl"
            - denom: "usmpl"
              exponent: 3
            - denom: "msmpl"
              exponent: 6
            - denom: "smpl"
              exponent: 9