swagger: '2.0'
info:
  title: HTTP API Console smplidentitychain.did
  name: ''
  description: ''
paths:
  /SmplEcosystem/SmplIdentityChain/did/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /SmplEcosystem/SmplIdentityChain/did/resolve_did_request/{did}:
    get:
      operationId: Query_ResolveDidRequest
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              didDocument:
                type: object
                properties:
                  contexts:
                    type: array
                    items:
                      type: string
                  id:
                    type: string
                  verification_method:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        controller:
                          type: string
                        public_key_base58:
                          type: string
                  authentication:
                    type: array
                    items:
                      type: object
                      properties:
                        verification_method_id:
                          type: string
                        verification_method:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            controller:
                              type: string
                            public_key_base58:
                              type: string
                  assertion_method:
                    type: array
                    items:
                      type: object
                      properties:
                        verification_method_id:
                          type: string
                        verification_method:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            controller:
                              type: string
                            public_key_base58:
                              type: string
                  key_agreement:
                    type: array
                    items:
                      type: object
                      properties:
                        verification_method_id:
                          type: string
                        verification_method:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            controller:
                              type: string
                            public_key_base58:
                              type: string
                  capability_invocation:
                    type: array
                    items:
                      type: object
                      properties:
                        verification_method_id:
                          type: string
                        verification_method:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            controller:
                              type: string
                            public_key_base58:
                              type: string
                  capability_delegation:
                    type: array
                    items:
                      type: object
                      properties:
                        verification_method_id:
                          type: string
                        verification_method:
                          type: object
                          properties:
                            id:
                              type: string
                            type:
                              type: string
                            controller:
                              type: string
                            public_key_base58:
                              type: string
                  services:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        service_endpoint:
                          type: string
              didResolutionMetadata:
                type: object
                properties:
                  contentType:
                    type: string
                  error:
                    type: string
              didDocumentMetadata:
                type: object
                properties:
                  created:
                    type: string
                  updated:
                    type: string
                  deactivated:
                    type: boolean
              sequence:
                type: string
                format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: did
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  DIDDocument:
    type: object
    properties:
      contexts:
        type: array
        items:
          type: string
      id:
        type: string
      verification_method:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            controller:
              type: string
            public_key_base58:
              type: string
      authentication:
        type: array
        items:
          type: object
          properties:
            verification_method_id:
              type: string
            verification_method:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
      assertion_method:
        type: array
        items:
          type: object
          properties:
            verification_method_id:
              type: string
            verification_method:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
      key_agreement:
        type: array
        items:
          type: object
          properties:
            verification_method_id:
              type: string
            verification_method:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
      capability_invocation:
        type: array
        items:
          type: object
          properties:
            verification_method_id:
              type: string
            verification_method:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
      capability_delegation:
        type: array
        items:
          type: object
          properties:
            verification_method_id:
              type: string
            verification_method:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
      services:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            service_endpoint:
              type: string
  DidDocumentMetadata:
    type: object
    properties:
      created:
        type: string
      updated:
        type: string
      deactivated:
        type: boolean
  DidResolutionMetadata:
    type: object
    properties:
      contentType:
        type: string
      error:
        type: string
  Params:
    type: object
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  QueryResolveDidResponse:
    type: object
    properties:
      didDocument:
        type: object
        properties:
          contexts:
            type: array
            items:
              type: string
          id:
            type: string
          verification_method:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                public_key_base58:
                  type: string
          authentication:
            type: array
            items:
              type: object
              properties:
                verification_method_id:
                  type: string
                verification_method:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    controller:
                      type: string
                    public_key_base58:
                      type: string
          assertion_method:
            type: array
            items:
              type: object
              properties:
                verification_method_id:
                  type: string
                verification_method:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    controller:
                      type: string
                    public_key_base58:
                      type: string
          key_agreement:
            type: array
            items:
              type: object
              properties:
                verification_method_id:
                  type: string
                verification_method:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    controller:
                      type: string
                    public_key_base58:
                      type: string
          capability_invocation:
            type: array
            items:
              type: object
              properties:
                verification_method_id:
                  type: string
                verification_method:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    controller:
                      type: string
                    public_key_base58:
                      type: string
          capability_delegation:
            type: array
            items:
              type: object
              properties:
                verification_method_id:
                  type: string
                verification_method:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    controller:
                      type: string
                    public_key_base58:
                      type: string
          services:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                service_endpoint:
                  type: string
      didResolutionMetadata:
        type: object
        properties:
          contentType:
            type: string
          error:
            type: string
      didDocumentMetadata:
        type: object
        properties:
          created:
            type: string
          updated:
            type: string
          deactivated:
            type: boolean
      sequence:
        type: string
        format: uint64
  Service:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      service_endpoint:
        type: string
  VerificationMethod:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      controller:
        type: string
      public_key_base58:
        type: string
  VerificationRelationship:
    type: object
    properties:
      verification_method_id:
        type: string
      verification_method:
        type: object
        properties:
          id:
            type: string
          type:
            type: string
          controller:
            type: string
          public_key_base58:
            type: string
  MsgUpdateParamsResponse:
    type: object
  MsgUpsertDidResponse:
    type: object
