// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/smplidentitychain/did/tx";
import { Params } from "./types/smplidentitychain/did/params";
import { GenesisState } from "./types/smplidentitychain/did/genesis";
import { ResolutionOptions } from "./types/smplidentitychain/did/resolution_options";
import { DidInfo } from "./types/smplidentitychain/did/did_info";
import { Service } from "./types/smplidentitychain/did/service";
import { MsgUpsertDid } from "./types/smplidentitychain/did/tx";
import { QueryParamsResponse } from "./types/smplidentitychain/did/query";
import { MsgUpdateParamsResponse } from "./types/smplidentitychain/did/tx";
import { MsgUpsertDidResponse } from "./types/smplidentitychain/did/tx";
import { DidDocumentMetadata } from "./types/smplidentitychain/did/did_document_metadata";
import { DidResolutionMetadata } from "./types/smplidentitychain/did/did_resolution_metadata";
import { DataWithSequence } from "./types/smplidentitychain/did/data_with_sequence";
import { VerificationRelationship } from "./types/smplidentitychain/did/verification_relationship";
import { QueryResolveDidResponse } from "./types/smplidentitychain/did/query";
import { VerificationMethod } from "./types/smplidentitychain/did/verification_method";
import { DIDDocument } from "./types/smplidentitychain/did/did_document";
import { QueryParamsRequest } from "./types/smplidentitychain/did/query";
import { QueryResolveDidRequest } from "./types/smplidentitychain/did/query";


export { MsgUpdateParams, Params, GenesisState, ResolutionOptions, DidInfo, Service, MsgUpsertDid, QueryParamsResponse, MsgUpdateParamsResponse, MsgUpsertDidResponse, DidDocumentMetadata, DidResolutionMetadata, DataWithSequence, VerificationRelationship, QueryResolveDidResponse, VerificationMethod, DIDDocument, QueryParamsRequest, QueryResolveDidRequest };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendResolutionOptionsParams = {
  value: ResolutionOptions,
  fee?: StdFee,
  memo?: string
};

type sendDidInfoParams = {
  value: DidInfo,
  fee?: StdFee,
  memo?: string
};

type sendServiceParams = {
  value: Service,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpsertDidParams = {
  value: MsgUpsertDid,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpsertDidResponseParams = {
  value: MsgUpsertDidResponse,
  fee?: StdFee,
  memo?: string
};

type sendDidDocumentMetadataParams = {
  value: DidDocumentMetadata,
  fee?: StdFee,
  memo?: string
};

type sendDidResolutionMetadataParams = {
  value: DidResolutionMetadata,
  fee?: StdFee,
  memo?: string
};

type sendDataWithSequenceParams = {
  value: DataWithSequence,
  fee?: StdFee,
  memo?: string
};

type sendVerificationRelationshipParams = {
  value: VerificationRelationship,
  fee?: StdFee,
  memo?: string
};

type sendQueryResolveDidResponseParams = {
  value: QueryResolveDidResponse,
  fee?: StdFee,
  memo?: string
};

type sendVerificationMethodParams = {
  value: VerificationMethod,
  fee?: StdFee,
  memo?: string
};

type sendDIDDocumentParams = {
  value: DIDDocument,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryResolveDidRequestParams = {
  value: QueryResolveDidRequest,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type paramsParams = {
  value: Params,
};

type genesisStateParams = {
  value: GenesisState,
};

type resolutionOptionsParams = {
  value: ResolutionOptions,
};

type didInfoParams = {
  value: DidInfo,
};

type serviceParams = {
  value: Service,
};

type msgUpsertDidParams = {
  value: MsgUpsertDid,
};

type queryParamsResponseParams = {
  value: QueryParamsResponse,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type msgUpsertDidResponseParams = {
  value: MsgUpsertDidResponse,
};

type didDocumentMetadataParams = {
  value: DidDocumentMetadata,
};

type didResolutionMetadataParams = {
  value: DidResolutionMetadata,
};

type dataWithSequenceParams = {
  value: DataWithSequence,
};

type verificationRelationshipParams = {
  value: VerificationRelationship,
};

type queryResolveDidResponseParams = {
  value: QueryResolveDidResponse,
};

type verificationMethodParams = {
  value: VerificationMethod,
};

type diddocumentParams = {
  value: DIDDocument,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type queryResolveDidRequestParams = {
  value: QueryResolveDidRequest,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendResolutionOptions({ value, fee, memo }: sendResolutionOptionsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendResolutionOptions: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.resolutionOptions({ value: ResolutionOptions.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendResolutionOptions: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDidInfo({ value, fee, memo }: sendDidInfoParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDidInfo: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.didInfo({ value: DidInfo.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDidInfo: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendService({ value, fee, memo }: sendServiceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendService: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.service({ value: Service.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendService: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpsertDid({ value, fee, memo }: sendMsgUpsertDidParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpsertDid: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpsertDid({ value: MsgUpsertDid.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpsertDid: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpsertDidResponse({ value, fee, memo }: sendMsgUpsertDidResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpsertDidResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpsertDidResponse({ value: MsgUpsertDidResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpsertDidResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDidDocumentMetadata({ value, fee, memo }: sendDidDocumentMetadataParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDidDocumentMetadata: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.didDocumentMetadata({ value: DidDocumentMetadata.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDidDocumentMetadata: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDidResolutionMetadata({ value, fee, memo }: sendDidResolutionMetadataParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDidResolutionMetadata: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.didResolutionMetadata({ value: DidResolutionMetadata.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDidResolutionMetadata: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDataWithSequence({ value, fee, memo }: sendDataWithSequenceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDataWithSequence: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.dataWithSequence({ value: DataWithSequence.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDataWithSequence: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendVerificationRelationship({ value, fee, memo }: sendVerificationRelationshipParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendVerificationRelationship: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.verificationRelationship({ value: VerificationRelationship.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendVerificationRelationship: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryResolveDidResponse({ value, fee, memo }: sendQueryResolveDidResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryResolveDidResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryResolveDidResponse({ value: QueryResolveDidResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryResolveDidResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendVerificationMethod({ value, fee, memo }: sendVerificationMethodParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendVerificationMethod: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.verificationMethod({ value: VerificationMethod.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendVerificationMethod: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDIDDocument({ value, fee, memo }: sendDIDDocumentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDIDDocument: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.diddocument({ value: DIDDocument.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDIDDocument: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryResolveDidRequest({ value, fee, memo }: sendQueryResolveDidRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryResolveDidRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryResolveDidRequest({ value: QueryResolveDidRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryResolveDidRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		resolutionOptions({ value }: resolutionOptionsParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.ResolutionOptions", value: ResolutionOptions.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:ResolutionOptions: Could not create message: ' + e.message)
			}
		},
		
		didInfo({ value }: didInfoParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.DidInfo", value: DidInfo.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DidInfo: Could not create message: ' + e.message)
			}
		},
		
		service({ value }: serviceParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.Service", value: Service.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Service: Could not create message: ' + e.message)
			}
		},
		
		msgUpsertDid({ value }: msgUpsertDidParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.MsgUpsertDid", value: MsgUpsertDid.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpsertDid: Could not create message: ' + e.message)
			}
		},
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpsertDidResponse({ value }: msgUpsertDidResponseParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.MsgUpsertDidResponse", value: MsgUpsertDidResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpsertDidResponse: Could not create message: ' + e.message)
			}
		},
		
		didDocumentMetadata({ value }: didDocumentMetadataParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.DidDocumentMetadata", value: DidDocumentMetadata.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DidDocumentMetadata: Could not create message: ' + e.message)
			}
		},
		
		didResolutionMetadata({ value }: didResolutionMetadataParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.DidResolutionMetadata", value: DidResolutionMetadata.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DidResolutionMetadata: Could not create message: ' + e.message)
			}
		},
		
		dataWithSequence({ value }: dataWithSequenceParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.DataWithSequence", value: DataWithSequence.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DataWithSequence: Could not create message: ' + e.message)
			}
		},
		
		verificationRelationship({ value }: verificationRelationshipParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.VerificationRelationship", value: VerificationRelationship.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:VerificationRelationship: Could not create message: ' + e.message)
			}
		},
		
		queryResolveDidResponse({ value }: queryResolveDidResponseParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.QueryResolveDidResponse", value: QueryResolveDidResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryResolveDidResponse: Could not create message: ' + e.message)
			}
		},
		
		verificationMethod({ value }: verificationMethodParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.VerificationMethod", value: VerificationMethod.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:VerificationMethod: Could not create message: ' + e.message)
			}
		},
		
		diddocument({ value }: diddocumentParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.DIDDocument", value: DIDDocument.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DIDDocument: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		queryResolveDidRequest({ value }: queryResolveDidRequestParams): EncodeObject {
			try {
				return { typeUrl: "/smplidentitychain.did.QueryResolveDidRequest", value: QueryResolveDidRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryResolveDidRequest: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			SmplidentitychainDid: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;