// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package did

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_DidDocumentMetadata             protoreflect.MessageDescriptor
	fd_DidDocumentMetadata_created     protoreflect.FieldDescriptor
	fd_DidDocumentMetadata_updated     protoreflect.FieldDescriptor
	fd_DidDocumentMetadata_deactivated protoreflect.FieldDescriptor
	fd_DidDocumentMetadata_versionId   protoreflect.FieldDescriptor
)

func init() {
	file_smplidentitychain_did_did_document_metadata_proto_init()
	md_DidDocumentMetadata = File_smplidentitychain_did_did_document_metadata_proto.Messages().ByName("DidDocumentMetadata")
	fd_DidDocumentMetadata_created = md_DidDocumentMetadata.Fields().ByName("created")
	fd_DidDocumentMetadata_updated = md_DidDocumentMetadata.Fields().ByName("updated")
	fd_DidDocumentMetadata_deactivated = md_DidDocumentMetadata.Fields().ByName("deactivated")
	fd_DidDocumentMetadata_versionId = md_DidDocumentMetadata.Fields().ByName("versionId")
}

var _ protoreflect.Message = (*fastReflection_DidDocumentMetadata)(nil)

type fastReflection_DidDocumentMetadata DidDocumentMetadata

func (x *DidDocumentMetadata) ProtoReflect() protoreflect.Message {
	return (*fastReflection_DidDocumentMetadata)(x)
}

func (x *DidDocumentMetadata) slowProtoReflect() protoreflect.Message {
	mi := &file_smplidentitychain_did_did_document_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_DidDocumentMetadata_messageType fastReflection_DidDocumentMetadata_messageType
var _ protoreflect.MessageType = fastReflection_DidDocumentMetadata_messageType{}

type fastReflection_DidDocumentMetadata_messageType struct{}

func (x fastReflection_DidDocumentMetadata_messageType) Zero() protoreflect.Message {
	return (*fastReflection_DidDocumentMetadata)(nil)
}
func (x fastReflection_DidDocumentMetadata_messageType) New() protoreflect.Message {
	return new(fastReflection_DidDocumentMetadata)
}
func (x fastReflection_DidDocumentMetadata_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_DidDocumentMetadata
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_DidDocumentMetadata) Descriptor() protoreflect.MessageDescriptor {
	return md_DidDocumentMetadata
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_DidDocumentMetadata) Type() protoreflect.MessageType {
	return _fastReflection_DidDocumentMetadata_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_DidDocumentMetadata) New() protoreflect.Message {
	return new(fastReflection_DidDocumentMetadata)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_DidDocumentMetadata) Interface() protoreflect.ProtoMessage {
	return (*DidDocumentMetadata)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_DidDocumentMetadata) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Created != "" {
		value := protoreflect.ValueOfString(x.Created)
		if !f(fd_DidDocumentMetadata_created, value) {
			return
		}
	}
	if x.Updated != "" {
		value := protoreflect.ValueOfString(x.Updated)
		if !f(fd_DidDocumentMetadata_updated, value) {
			return
		}
	}
	if x.Deactivated != false {
		value := protoreflect.ValueOfBool(x.Deactivated)
		if !f(fd_DidDocumentMetadata_deactivated, value) {
			return
		}
	}
	if x.VersionId != "" {
		value := protoreflect.ValueOfString(x.VersionId)
		if !f(fd_DidDocumentMetadata_versionId, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_DidDocumentMetadata) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		return x.Created != ""
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		return x.Updated != ""
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		return x.Deactivated != false
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		return x.VersionId != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DidDocumentMetadata) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		x.Created = ""
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		x.Updated = ""
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		x.Deactivated = false
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		x.VersionId = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_DidDocumentMetadata) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		value := x.Created
		return protoreflect.ValueOfString(value)
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		value := x.Updated
		return protoreflect.ValueOfString(value)
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		value := x.Deactivated
		return protoreflect.ValueOfBool(value)
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		value := x.VersionId
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DidDocumentMetadata) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		x.Created = value.Interface().(string)
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		x.Updated = value.Interface().(string)
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		x.Deactivated = value.Bool()
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		x.VersionId = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DidDocumentMetadata) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		panic(fmt.Errorf("field created of message smplidentitychain.did.DidDocumentMetadata is not mutable"))
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		panic(fmt.Errorf("field updated of message smplidentitychain.did.DidDocumentMetadata is not mutable"))
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		panic(fmt.Errorf("field deactivated of message smplidentitychain.did.DidDocumentMetadata is not mutable"))
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		panic(fmt.Errorf("field versionId of message smplidentitychain.did.DidDocumentMetadata is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_DidDocumentMetadata) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.DidDocumentMetadata.created":
		return protoreflect.ValueOfString("")
	case "smplidentitychain.did.DidDocumentMetadata.updated":
		return protoreflect.ValueOfString("")
	case "smplidentitychain.did.DidDocumentMetadata.deactivated":
		return protoreflect.ValueOfBool(false)
	case "smplidentitychain.did.DidDocumentMetadata.versionId":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DidDocumentMetadata"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DidDocumentMetadata does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_DidDocumentMetadata) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in smplidentitychain.did.DidDocumentMetadata", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_DidDocumentMetadata) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DidDocumentMetadata) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_DidDocumentMetadata) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_DidDocumentMetadata) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*DidDocumentMetadata)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Created)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Updated)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Deactivated {
			n += 2
		}
		l = len(x.VersionId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*DidDocumentMetadata)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.VersionId) > 0 {
			i -= len(x.VersionId)
			copy(dAtA[i:], x.VersionId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VersionId)))
			i--
			dAtA[i] = 0x22
		}
		if x.Deactivated {
			i--
			if x.Deactivated {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x18
		}
		if len(x.Updated) > 0 {
			i -= len(x.Updated)
			copy(dAtA[i:], x.Updated)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Updated)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Created) > 0 {
			i -= len(x.Created)
			copy(dAtA[i:], x.Created)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Created)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*DidDocumentMetadata)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DidDocumentMetadata: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DidDocumentMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Created = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Updated = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Deactivated", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Deactivated = bool(v != 0)
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VersionId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VersionId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: smplidentitychain/did/did_document_metadata.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DidDocumentMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created     string `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated     string `protobuf:"bytes,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Deactivated bool   `protobuf:"varint,3,opt,name=deactivated,proto3" json:"deactivated,omitempty"`
	VersionId   string `protobuf:"bytes,4,opt,name=versionId,proto3" json:"versionId,omitempty"`
}

func (x *DidDocumentMetadata) Reset() {
	*x = DidDocumentMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smplidentitychain_did_did_document_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DidDocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DidDocumentMetadata) ProtoMessage() {}

// Deprecated: Use DidDocumentMetadata.ProtoReflect.Descriptor instead.
func (*DidDocumentMetadata) Descriptor() ([]byte, []int) {
	return file_smplidentitychain_did_did_document_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DidDocumentMetadata) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *DidDocumentMetadata) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *DidDocumentMetadata) GetDeactivated() bool {
	if x != nil {
		return x.Deactivated
	}
	return false
}

func (x *DidDocumentMetadata) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

var File_smplidentitychain_did_did_document_metadata_proto protoreflect.FileDescriptor

var file_smplidentitychain_did_did_document_metadata_proto_rawDesc = []byte{
	0x0a, 0x31, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x64, 0x69, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x13, 0x44,
	0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x64, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0xd2, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x64, 0x69, 0x64, 0x42, 0x18, 0x44, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x26, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0xa2, 0x02, 0x03, 0x53, 0x44, 0x58, 0xaa, 0x02,
	0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x44, 0x69, 0x64, 0xca, 0x02, 0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0xe2, 0x02,
	0x21, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x16, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x44, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_smplidentitychain_did_did_document_metadata_proto_rawDescOnce sync.Once
	file_smplidentitychain_did_did_document_metadata_proto_rawDescData = file_smplidentitychain_did_did_document_metadata_proto_rawDesc
)

func file_smplidentitychain_did_did_document_metadata_proto_rawDescGZIP() []byte {
	file_smplidentitychain_did_did_document_metadata_proto_rawDescOnce.Do(func() {
		file_smplidentitychain_did_did_document_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_smplidentitychain_did_did_document_metadata_proto_rawDescData)
	})
	return file_smplidentitychain_did_did_document_metadata_proto_rawDescData
}

var file_smplidentitychain_did_did_document_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smplidentitychain_did_did_document_metadata_proto_goTypes = []interface{}{
	(*DidDocumentMetadata)(nil), // 0: smplidentitychain.did.DidDocumentMetadata
}
var file_smplidentitychain_did_did_document_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smplidentitychain_did_did_document_metadata_proto_init() }
func file_smplidentitychain_did_did_document_metadata_proto_init() {
	if File_smplidentitychain_did_did_document_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smplidentitychain_did_did_document_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DidDocumentMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smplidentitychain_did_did_document_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smplidentitychain_did_did_document_metadata_proto_goTypes,
		DependencyIndexes: file_smplidentitychain_did_did_document_metadata_proto_depIdxs,
		MessageInfos:      file_smplidentitychain_did_did_document_metadata_proto_msgTypes,
	}.Build()
	File_smplidentitychain_did_did_document_metadata_proto = out.File
	file_smplidentitychain_did_did_document_metadata_proto_rawDesc = nil
	file_smplidentitychain_did_did_document_metadata_proto_goTypes = nil
	file_smplidentitychain_did_did_document_metadata_proto_depIdxs = nil
}
