// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package did

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_DIDDocument_1_list)(nil)

type _DIDDocument_1_list struct {
	list *[]string
}

func (x *_DIDDocument_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_DIDDocument_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_1_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message DIDDocument at list field Contexts as it is not of Message kind"))
}

func (x *_DIDDocument_1_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_1_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_DIDDocument_1_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_3_list)(nil)

type _DIDDocument_3_list struct {
	list *[]*VerificationMethod
}

func (x *_DIDDocument_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationMethod)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationMethod)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_3_list) AppendMutable() protoreflect.Value {
	v := new(VerificationMethod)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_3_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_3_list) NewElement() protoreflect.Value {
	v := new(VerificationMethod)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_3_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_4_list)(nil)

type _DIDDocument_4_list struct {
	list *[]*VerificationRelationship
}

func (x *_DIDDocument_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_4_list) AppendMutable() protoreflect.Value {
	v := new(VerificationRelationship)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_4_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_4_list) NewElement() protoreflect.Value {
	v := new(VerificationRelationship)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_4_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_5_list)(nil)

type _DIDDocument_5_list struct {
	list *[]*VerificationRelationship
}

func (x *_DIDDocument_5_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_5_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_5_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_5_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_5_list) AppendMutable() protoreflect.Value {
	v := new(VerificationRelationship)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_5_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_5_list) NewElement() protoreflect.Value {
	v := new(VerificationRelationship)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_5_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_6_list)(nil)

type _DIDDocument_6_list struct {
	list *[]*VerificationRelationship
}

func (x *_DIDDocument_6_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_6_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_6_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_6_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_6_list) AppendMutable() protoreflect.Value {
	v := new(VerificationRelationship)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_6_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_6_list) NewElement() protoreflect.Value {
	v := new(VerificationRelationship)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_6_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_7_list)(nil)

type _DIDDocument_7_list struct {
	list *[]*VerificationRelationship
}

func (x *_DIDDocument_7_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_7_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_7_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_7_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_7_list) AppendMutable() protoreflect.Value {
	v := new(VerificationRelationship)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_7_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_7_list) NewElement() protoreflect.Value {
	v := new(VerificationRelationship)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_7_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_8_list)(nil)

type _DIDDocument_8_list struct {
	list *[]*VerificationRelationship
}

func (x *_DIDDocument_8_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_8_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_8_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_8_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*VerificationRelationship)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_8_list) AppendMutable() protoreflect.Value {
	v := new(VerificationRelationship)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_8_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_8_list) NewElement() protoreflect.Value {
	v := new(VerificationRelationship)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_8_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_DIDDocument_9_list)(nil)

type _DIDDocument_9_list struct {
	list *[]*Service
}

func (x *_DIDDocument_9_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_DIDDocument_9_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_DIDDocument_9_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Service)
	(*x.list)[i] = concreteValue
}

func (x *_DIDDocument_9_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Service)
	*x.list = append(*x.list, concreteValue)
}

func (x *_DIDDocument_9_list) AppendMutable() protoreflect.Value {
	v := new(Service)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_9_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_DIDDocument_9_list) NewElement() protoreflect.Value {
	v := new(Service)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_DIDDocument_9_list) IsValid() bool {
	return x.list != nil
}

var (
	md_DIDDocument                        protoreflect.MessageDescriptor
	fd_DIDDocument_contexts               protoreflect.FieldDescriptor
	fd_DIDDocument_id                     protoreflect.FieldDescriptor
	fd_DIDDocument_verification_methods   protoreflect.FieldDescriptor
	fd_DIDDocument_authentications        protoreflect.FieldDescriptor
	fd_DIDDocument_assertion_methods      protoreflect.FieldDescriptor
	fd_DIDDocument_key_agreements         protoreflect.FieldDescriptor
	fd_DIDDocument_capability_invocations protoreflect.FieldDescriptor
	fd_DIDDocument_capability_delegations protoreflect.FieldDescriptor
	fd_DIDDocument_services               protoreflect.FieldDescriptor
)

func init() {
	file_smplidentitychain_did_did_document_proto_init()
	md_DIDDocument = File_smplidentitychain_did_did_document_proto.Messages().ByName("DIDDocument")
	fd_DIDDocument_contexts = md_DIDDocument.Fields().ByName("contexts")
	fd_DIDDocument_id = md_DIDDocument.Fields().ByName("id")
	fd_DIDDocument_verification_methods = md_DIDDocument.Fields().ByName("verification_methods")
	fd_DIDDocument_authentications = md_DIDDocument.Fields().ByName("authentications")
	fd_DIDDocument_assertion_methods = md_DIDDocument.Fields().ByName("assertion_methods")
	fd_DIDDocument_key_agreements = md_DIDDocument.Fields().ByName("key_agreements")
	fd_DIDDocument_capability_invocations = md_DIDDocument.Fields().ByName("capability_invocations")
	fd_DIDDocument_capability_delegations = md_DIDDocument.Fields().ByName("capability_delegations")
	fd_DIDDocument_services = md_DIDDocument.Fields().ByName("services")
}

var _ protoreflect.Message = (*fastReflection_DIDDocument)(nil)

type fastReflection_DIDDocument DIDDocument

func (x *DIDDocument) ProtoReflect() protoreflect.Message {
	return (*fastReflection_DIDDocument)(x)
}

func (x *DIDDocument) slowProtoReflect() protoreflect.Message {
	mi := &file_smplidentitychain_did_did_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_DIDDocument_messageType fastReflection_DIDDocument_messageType
var _ protoreflect.MessageType = fastReflection_DIDDocument_messageType{}

type fastReflection_DIDDocument_messageType struct{}

func (x fastReflection_DIDDocument_messageType) Zero() protoreflect.Message {
	return (*fastReflection_DIDDocument)(nil)
}
func (x fastReflection_DIDDocument_messageType) New() protoreflect.Message {
	return new(fastReflection_DIDDocument)
}
func (x fastReflection_DIDDocument_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_DIDDocument
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_DIDDocument) Descriptor() protoreflect.MessageDescriptor {
	return md_DIDDocument
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_DIDDocument) Type() protoreflect.MessageType {
	return _fastReflection_DIDDocument_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_DIDDocument) New() protoreflect.Message {
	return new(fastReflection_DIDDocument)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_DIDDocument) Interface() protoreflect.ProtoMessage {
	return (*DIDDocument)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_DIDDocument) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Contexts) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_1_list{list: &x.Contexts})
		if !f(fd_DIDDocument_contexts, value) {
			return
		}
	}
	if x.Id != "" {
		value := protoreflect.ValueOfString(x.Id)
		if !f(fd_DIDDocument_id, value) {
			return
		}
	}
	if len(x.VerificationMethods) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_3_list{list: &x.VerificationMethods})
		if !f(fd_DIDDocument_verification_methods, value) {
			return
		}
	}
	if len(x.Authentications) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_4_list{list: &x.Authentications})
		if !f(fd_DIDDocument_authentications, value) {
			return
		}
	}
	if len(x.AssertionMethods) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_5_list{list: &x.AssertionMethods})
		if !f(fd_DIDDocument_assertion_methods, value) {
			return
		}
	}
	if len(x.KeyAgreements) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_6_list{list: &x.KeyAgreements})
		if !f(fd_DIDDocument_key_agreements, value) {
			return
		}
	}
	if len(x.CapabilityInvocations) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_7_list{list: &x.CapabilityInvocations})
		if !f(fd_DIDDocument_capability_invocations, value) {
			return
		}
	}
	if len(x.CapabilityDelegations) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_8_list{list: &x.CapabilityDelegations})
		if !f(fd_DIDDocument_capability_delegations, value) {
			return
		}
	}
	if len(x.Services) != 0 {
		value := protoreflect.ValueOfList(&_DIDDocument_9_list{list: &x.Services})
		if !f(fd_DIDDocument_services, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_DIDDocument) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		return len(x.Contexts) != 0
	case "smplidentitychain.did.DIDDocument.id":
		return x.Id != ""
	case "smplidentitychain.did.DIDDocument.verification_methods":
		return len(x.VerificationMethods) != 0
	case "smplidentitychain.did.DIDDocument.authentications":
		return len(x.Authentications) != 0
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		return len(x.AssertionMethods) != 0
	case "smplidentitychain.did.DIDDocument.key_agreements":
		return len(x.KeyAgreements) != 0
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		return len(x.CapabilityInvocations) != 0
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		return len(x.CapabilityDelegations) != 0
	case "smplidentitychain.did.DIDDocument.services":
		return len(x.Services) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DIDDocument) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		x.Contexts = nil
	case "smplidentitychain.did.DIDDocument.id":
		x.Id = ""
	case "smplidentitychain.did.DIDDocument.verification_methods":
		x.VerificationMethods = nil
	case "smplidentitychain.did.DIDDocument.authentications":
		x.Authentications = nil
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		x.AssertionMethods = nil
	case "smplidentitychain.did.DIDDocument.key_agreements":
		x.KeyAgreements = nil
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		x.CapabilityInvocations = nil
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		x.CapabilityDelegations = nil
	case "smplidentitychain.did.DIDDocument.services":
		x.Services = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_DIDDocument) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		if len(x.Contexts) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_1_list{})
		}
		listValue := &_DIDDocument_1_list{list: &x.Contexts}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.id":
		value := x.Id
		return protoreflect.ValueOfString(value)
	case "smplidentitychain.did.DIDDocument.verification_methods":
		if len(x.VerificationMethods) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_3_list{})
		}
		listValue := &_DIDDocument_3_list{list: &x.VerificationMethods}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.authentications":
		if len(x.Authentications) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_4_list{})
		}
		listValue := &_DIDDocument_4_list{list: &x.Authentications}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		if len(x.AssertionMethods) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_5_list{})
		}
		listValue := &_DIDDocument_5_list{list: &x.AssertionMethods}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.key_agreements":
		if len(x.KeyAgreements) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_6_list{})
		}
		listValue := &_DIDDocument_6_list{list: &x.KeyAgreements}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		if len(x.CapabilityInvocations) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_7_list{})
		}
		listValue := &_DIDDocument_7_list{list: &x.CapabilityInvocations}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		if len(x.CapabilityDelegations) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_8_list{})
		}
		listValue := &_DIDDocument_8_list{list: &x.CapabilityDelegations}
		return protoreflect.ValueOfList(listValue)
	case "smplidentitychain.did.DIDDocument.services":
		if len(x.Services) == 0 {
			return protoreflect.ValueOfList(&_DIDDocument_9_list{})
		}
		listValue := &_DIDDocument_9_list{list: &x.Services}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DIDDocument) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		lv := value.List()
		clv := lv.(*_DIDDocument_1_list)
		x.Contexts = *clv.list
	case "smplidentitychain.did.DIDDocument.id":
		x.Id = value.Interface().(string)
	case "smplidentitychain.did.DIDDocument.verification_methods":
		lv := value.List()
		clv := lv.(*_DIDDocument_3_list)
		x.VerificationMethods = *clv.list
	case "smplidentitychain.did.DIDDocument.authentications":
		lv := value.List()
		clv := lv.(*_DIDDocument_4_list)
		x.Authentications = *clv.list
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		lv := value.List()
		clv := lv.(*_DIDDocument_5_list)
		x.AssertionMethods = *clv.list
	case "smplidentitychain.did.DIDDocument.key_agreements":
		lv := value.List()
		clv := lv.(*_DIDDocument_6_list)
		x.KeyAgreements = *clv.list
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		lv := value.List()
		clv := lv.(*_DIDDocument_7_list)
		x.CapabilityInvocations = *clv.list
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		lv := value.List()
		clv := lv.(*_DIDDocument_8_list)
		x.CapabilityDelegations = *clv.list
	case "smplidentitychain.did.DIDDocument.services":
		lv := value.List()
		clv := lv.(*_DIDDocument_9_list)
		x.Services = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DIDDocument) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		if x.Contexts == nil {
			x.Contexts = []string{}
		}
		value := &_DIDDocument_1_list{list: &x.Contexts}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.verification_methods":
		if x.VerificationMethods == nil {
			x.VerificationMethods = []*VerificationMethod{}
		}
		value := &_DIDDocument_3_list{list: &x.VerificationMethods}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.authentications":
		if x.Authentications == nil {
			x.Authentications = []*VerificationRelationship{}
		}
		value := &_DIDDocument_4_list{list: &x.Authentications}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		if x.AssertionMethods == nil {
			x.AssertionMethods = []*VerificationRelationship{}
		}
		value := &_DIDDocument_5_list{list: &x.AssertionMethods}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.key_agreements":
		if x.KeyAgreements == nil {
			x.KeyAgreements = []*VerificationRelationship{}
		}
		value := &_DIDDocument_6_list{list: &x.KeyAgreements}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		if x.CapabilityInvocations == nil {
			x.CapabilityInvocations = []*VerificationRelationship{}
		}
		value := &_DIDDocument_7_list{list: &x.CapabilityInvocations}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		if x.CapabilityDelegations == nil {
			x.CapabilityDelegations = []*VerificationRelationship{}
		}
		value := &_DIDDocument_8_list{list: &x.CapabilityDelegations}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.services":
		if x.Services == nil {
			x.Services = []*Service{}
		}
		value := &_DIDDocument_9_list{list: &x.Services}
		return protoreflect.ValueOfList(value)
	case "smplidentitychain.did.DIDDocument.id":
		panic(fmt.Errorf("field id of message smplidentitychain.did.DIDDocument is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_DIDDocument) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.DIDDocument.contexts":
		list := []string{}
		return protoreflect.ValueOfList(&_DIDDocument_1_list{list: &list})
	case "smplidentitychain.did.DIDDocument.id":
		return protoreflect.ValueOfString("")
	case "smplidentitychain.did.DIDDocument.verification_methods":
		list := []*VerificationMethod{}
		return protoreflect.ValueOfList(&_DIDDocument_3_list{list: &list})
	case "smplidentitychain.did.DIDDocument.authentications":
		list := []*VerificationRelationship{}
		return protoreflect.ValueOfList(&_DIDDocument_4_list{list: &list})
	case "smplidentitychain.did.DIDDocument.assertion_methods":
		list := []*VerificationRelationship{}
		return protoreflect.ValueOfList(&_DIDDocument_5_list{list: &list})
	case "smplidentitychain.did.DIDDocument.key_agreements":
		list := []*VerificationRelationship{}
		return protoreflect.ValueOfList(&_DIDDocument_6_list{list: &list})
	case "smplidentitychain.did.DIDDocument.capability_invocations":
		list := []*VerificationRelationship{}
		return protoreflect.ValueOfList(&_DIDDocument_7_list{list: &list})
	case "smplidentitychain.did.DIDDocument.capability_delegations":
		list := []*VerificationRelationship{}
		return protoreflect.ValueOfList(&_DIDDocument_8_list{list: &list})
	case "smplidentitychain.did.DIDDocument.services":
		list := []*Service{}
		return protoreflect.ValueOfList(&_DIDDocument_9_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.DIDDocument"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.DIDDocument does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_DIDDocument) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in smplidentitychain.did.DIDDocument", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_DIDDocument) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DIDDocument) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_DIDDocument) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_DIDDocument) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*DIDDocument)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Contexts) > 0 {
			for _, s := range x.Contexts {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.Id)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.VerificationMethods) > 0 {
			for _, e := range x.VerificationMethods {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Authentications) > 0 {
			for _, e := range x.Authentications {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.AssertionMethods) > 0 {
			for _, e := range x.AssertionMethods {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.KeyAgreements) > 0 {
			for _, e := range x.KeyAgreements {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.CapabilityInvocations) > 0 {
			for _, e := range x.CapabilityInvocations {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.CapabilityDelegations) > 0 {
			for _, e := range x.CapabilityDelegations {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Services) > 0 {
			for _, e := range x.Services {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*DIDDocument)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Services) > 0 {
			for iNdEx := len(x.Services) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Services[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x4a
			}
		}
		if len(x.CapabilityDelegations) > 0 {
			for iNdEx := len(x.CapabilityDelegations) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.CapabilityDelegations[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x42
			}
		}
		if len(x.CapabilityInvocations) > 0 {
			for iNdEx := len(x.CapabilityInvocations) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.CapabilityInvocations[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x3a
			}
		}
		if len(x.KeyAgreements) > 0 {
			for iNdEx := len(x.KeyAgreements) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.KeyAgreements[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x32
			}
		}
		if len(x.AssertionMethods) > 0 {
			for iNdEx := len(x.AssertionMethods) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.AssertionMethods[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x2a
			}
		}
		if len(x.Authentications) > 0 {
			for iNdEx := len(x.Authentications) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Authentications[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x22
			}
		}
		if len(x.VerificationMethods) > 0 {
			for iNdEx := len(x.VerificationMethods) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.VerificationMethods[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x1a
			}
		}
		if len(x.Id) > 0 {
			i -= len(x.Id)
			copy(dAtA[i:], x.Id)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Id)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Contexts) > 0 {
			for iNdEx := len(x.Contexts) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Contexts[iNdEx])
				copy(dAtA[i:], x.Contexts[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Contexts[iNdEx])))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*DIDDocument)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DIDDocument: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Contexts", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Contexts = append(x.Contexts, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Id = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VerificationMethods", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VerificationMethods = append(x.VerificationMethods, &VerificationMethod{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.VerificationMethods[len(x.VerificationMethods)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Authentications", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Authentications = append(x.Authentications, &VerificationRelationship{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Authentications[len(x.Authentications)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AssertionMethods", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AssertionMethods = append(x.AssertionMethods, &VerificationRelationship{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.AssertionMethods[len(x.AssertionMethods)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field KeyAgreements", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.KeyAgreements = append(x.KeyAgreements, &VerificationRelationship{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.KeyAgreements[len(x.KeyAgreements)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CapabilityInvocations", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CapabilityInvocations = append(x.CapabilityInvocations, &VerificationRelationship{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.CapabilityInvocations[len(x.CapabilityInvocations)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CapabilityDelegations", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CapabilityDelegations = append(x.CapabilityDelegations, &VerificationRelationship{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.CapabilityDelegations[len(x.CapabilityDelegations)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Services", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Services = append(x.Services, &Service{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Services[len(x.Services)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: smplidentitychain/did/did_document.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DIDDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contexts              []string                    `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	Id                    string                      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	VerificationMethods   []*VerificationMethod       `protobuf:"bytes,3,rep,name=verification_methods,json=verificationMethod,proto3" json:"verification_methods,omitempty"`
	Authentications       []*VerificationRelationship `protobuf:"bytes,4,rep,name=authentications,json=authentication,proto3" json:"authentications,omitempty"`
	AssertionMethods      []*VerificationRelationship `protobuf:"bytes,5,rep,name=assertion_methods,json=assertionMethod,proto3" json:"assertion_methods,omitempty"`
	KeyAgreements         []*VerificationRelationship `protobuf:"bytes,6,rep,name=key_agreements,json=keyAgreement,proto3" json:"key_agreements,omitempty"`
	CapabilityInvocations []*VerificationRelationship `protobuf:"bytes,7,rep,name=capability_invocations,json=capabilityInvocation,proto3" json:"capability_invocations,omitempty"`
	CapabilityDelegations []*VerificationRelationship `protobuf:"bytes,8,rep,name=capability_delegations,json=capabilityDelegation,proto3" json:"capability_delegations,omitempty"`
	Services              []*Service                  `protobuf:"bytes,9,rep,name=services,json=service,proto3" json:"services,omitempty"`
}

func (x *DIDDocument) Reset() {
	*x = DIDDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smplidentitychain_did_did_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DIDDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDDocument) ProtoMessage() {}

// Deprecated: Use DIDDocument.ProtoReflect.Descriptor instead.
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return file_smplidentitychain_did_did_document_proto_rawDescGZIP(), []int{0}
}

func (x *DIDDocument) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *DIDDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DIDDocument) GetVerificationMethods() []*VerificationMethod {
	if x != nil {
		return x.VerificationMethods
	}
	return nil
}

func (x *DIDDocument) GetAuthentications() []*VerificationRelationship {
	if x != nil {
		return x.Authentications
	}
	return nil
}

func (x *DIDDocument) GetAssertionMethods() []*VerificationRelationship {
	if x != nil {
		return x.AssertionMethods
	}
	return nil
}

func (x *DIDDocument) GetKeyAgreements() []*VerificationRelationship {
	if x != nil {
		return x.KeyAgreements
	}
	return nil
}

func (x *DIDDocument) GetCapabilityInvocations() []*VerificationRelationship {
	if x != nil {
		return x.CapabilityInvocations
	}
	return nil
}

func (x *DIDDocument) GetCapabilityDelegations() []*VerificationRelationship {
	if x != nil {
		return x.CapabilityDelegations
	}
	return nil
}

func (x *DIDDocument) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_smplidentitychain_did_did_document_proto protoreflect.FileDescriptor

var file_smplidentitychain_did_did_document_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x64, 0x69, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x6d, 0x70, 0x6c,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69,
	0x64, 0x1a, 0x23, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x35, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad,
	0x05, 0x0a, 0x0b, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x5b, 0x0a, 0x14, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x52, 0x12, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x58, 0x0a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x5b, 0x0a, 0x11, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73,
	0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0f, 0x61,
	0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x55,
	0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0c, 0x6b, 0x65, 0x79, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x65, 0x0a, 0x16, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x14, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x65, 0x0a, 0x16,
	0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73,
	0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x14, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0xca,
	0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x42, 0x10, 0x44, 0x69,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x26, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0xa2, 0x02, 0x03, 0x53, 0x44, 0x58, 0xaa, 0x02,
	0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x44, 0x69, 0x64, 0xca, 0x02, 0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0xe2, 0x02,
	0x21, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x16, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x44, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_smplidentitychain_did_did_document_proto_rawDescOnce sync.Once
	file_smplidentitychain_did_did_document_proto_rawDescData = file_smplidentitychain_did_did_document_proto_rawDesc
)

func file_smplidentitychain_did_did_document_proto_rawDescGZIP() []byte {
	file_smplidentitychain_did_did_document_proto_rawDescOnce.Do(func() {
		file_smplidentitychain_did_did_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_smplidentitychain_did_did_document_proto_rawDescData)
	})
	return file_smplidentitychain_did_did_document_proto_rawDescData
}

var file_smplidentitychain_did_did_document_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smplidentitychain_did_did_document_proto_goTypes = []interface{}{
	(*DIDDocument)(nil),              // 0: smplidentitychain.did.DIDDocument
	(*VerificationMethod)(nil),       // 1: smplidentitychain.did.VerificationMethod
	(*VerificationRelationship)(nil), // 2: smplidentitychain.did.VerificationRelationship
	(*Service)(nil),                  // 3: smplidentitychain.did.Service
}
var file_smplidentitychain_did_did_document_proto_depIdxs = []int32{
	1, // 0: smplidentitychain.did.DIDDocument.verification_methods:type_name -> smplidentitychain.did.VerificationMethod
	2, // 1: smplidentitychain.did.DIDDocument.authentications:type_name -> smplidentitychain.did.VerificationRelationship
	2, // 2: smplidentitychain.did.DIDDocument.assertion_methods:type_name -> smplidentitychain.did.VerificationRelationship
	2, // 3: smplidentitychain.did.DIDDocument.key_agreements:type_name -> smplidentitychain.did.VerificationRelationship
	2, // 4: smplidentitychain.did.DIDDocument.capability_invocations:type_name -> smplidentitychain.did.VerificationRelationship
	2, // 5: smplidentitychain.did.DIDDocument.capability_delegations:type_name -> smplidentitychain.did.VerificationRelationship
	3, // 6: smplidentitychain.did.DIDDocument.services:type_name -> smplidentitychain.did.Service
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_smplidentitychain_did_did_document_proto_init() }
func file_smplidentitychain_did_did_document_proto_init() {
	if File_smplidentitychain_did_did_document_proto != nil {
		return
	}
	file_smplidentitychain_did_service_proto_init()
	file_smplidentitychain_did_verification_method_proto_init()
	file_smplidentitychain_did_verification_relationship_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_smplidentitychain_did_did_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DIDDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smplidentitychain_did_did_document_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smplidentitychain_did_did_document_proto_goTypes,
		DependencyIndexes: file_smplidentitychain_did_did_document_proto_depIdxs,
		MessageInfos:      file_smplidentitychain_did_did_document_proto_msgTypes,
	}.Build()
	File_smplidentitychain_did_did_document_proto = out.File
	file_smplidentitychain_did_did_document_proto_rawDesc = nil
	file_smplidentitychain_did_did_document_proto_goTypes = nil
	file_smplidentitychain_did_did_document_proto_depIdxs = nil
}
