// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package did

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_ResolveDidRequestResponse                       protoreflect.MessageDescriptor
	fd_ResolveDidRequestResponse_didDocument           protoreflect.FieldDescriptor
	fd_ResolveDidRequestResponse_didResolutionMetadata protoreflect.FieldDescriptor
	fd_ResolveDidRequestResponse_didDocumentMetadata   protoreflect.FieldDescriptor
)

func init() {
	file_smplidentitychain_did_resolve_did_request_response_proto_init()
	md_ResolveDidRequestResponse = File_smplidentitychain_did_resolve_did_request_response_proto.Messages().ByName("ResolveDidRequestResponse")
	fd_ResolveDidRequestResponse_didDocument = md_ResolveDidRequestResponse.Fields().ByName("didDocument")
	fd_ResolveDidRequestResponse_didResolutionMetadata = md_ResolveDidRequestResponse.Fields().ByName("didResolutionMetadata")
	fd_ResolveDidRequestResponse_didDocumentMetadata = md_ResolveDidRequestResponse.Fields().ByName("didDocumentMetadata")
}

var _ protoreflect.Message = (*fastReflection_ResolveDidRequestResponse)(nil)

type fastReflection_ResolveDidRequestResponse ResolveDidRequestResponse

func (x *ResolveDidRequestResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ResolveDidRequestResponse)(x)
}

func (x *ResolveDidRequestResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_smplidentitychain_did_resolve_did_request_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ResolveDidRequestResponse_messageType fastReflection_ResolveDidRequestResponse_messageType
var _ protoreflect.MessageType = fastReflection_ResolveDidRequestResponse_messageType{}

type fastReflection_ResolveDidRequestResponse_messageType struct{}

func (x fastReflection_ResolveDidRequestResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ResolveDidRequestResponse)(nil)
}
func (x fastReflection_ResolveDidRequestResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_ResolveDidRequestResponse)
}
func (x fastReflection_ResolveDidRequestResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ResolveDidRequestResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ResolveDidRequestResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_ResolveDidRequestResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ResolveDidRequestResponse) Type() protoreflect.MessageType {
	return _fastReflection_ResolveDidRequestResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ResolveDidRequestResponse) New() protoreflect.Message {
	return new(fastReflection_ResolveDidRequestResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ResolveDidRequestResponse) Interface() protoreflect.ProtoMessage {
	return (*ResolveDidRequestResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ResolveDidRequestResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.DidDocument != nil {
		value := protoreflect.ValueOfMessage(x.DidDocument.ProtoReflect())
		if !f(fd_ResolveDidRequestResponse_didDocument, value) {
			return
		}
	}
	if x.DidResolutionMetadata != nil {
		value := protoreflect.ValueOfMessage(x.DidResolutionMetadata.ProtoReflect())
		if !f(fd_ResolveDidRequestResponse_didResolutionMetadata, value) {
			return
		}
	}
	if x.DidDocumentMetadata != nil {
		value := protoreflect.ValueOfMessage(x.DidDocumentMetadata.ProtoReflect())
		if !f(fd_ResolveDidRequestResponse_didDocumentMetadata, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ResolveDidRequestResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		return x.DidDocument != nil
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		return x.DidResolutionMetadata != nil
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		return x.DidDocumentMetadata != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResolveDidRequestResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		x.DidDocument = nil
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		x.DidResolutionMetadata = nil
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		x.DidDocumentMetadata = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ResolveDidRequestResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		value := x.DidDocument
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		value := x.DidResolutionMetadata
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		value := x.DidDocumentMetadata
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResolveDidRequestResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		x.DidDocument = value.Message().Interface().(*DIDDocument)
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		x.DidResolutionMetadata = value.Message().Interface().(*DidResolutionMetadata)
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		x.DidDocumentMetadata = value.Message().Interface().(*DidDocumentMetadata)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResolveDidRequestResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		if x.DidDocument == nil {
			x.DidDocument = new(DIDDocument)
		}
		return protoreflect.ValueOfMessage(x.DidDocument.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		if x.DidResolutionMetadata == nil {
			x.DidResolutionMetadata = new(DidResolutionMetadata)
		}
		return protoreflect.ValueOfMessage(x.DidResolutionMetadata.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		if x.DidDocumentMetadata == nil {
			x.DidDocumentMetadata = new(DidDocumentMetadata)
		}
		return protoreflect.ValueOfMessage(x.DidDocumentMetadata.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ResolveDidRequestResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocument":
		m := new(DIDDocument)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata":
		m := new(DidResolutionMetadata)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata":
		m := new(DidDocumentMetadata)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.ResolveDidRequestResponse"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.ResolveDidRequestResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ResolveDidRequestResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in smplidentitychain.did.ResolveDidRequestResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ResolveDidRequestResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResolveDidRequestResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ResolveDidRequestResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ResolveDidRequestResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ResolveDidRequestResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.DidDocument != nil {
			l = options.Size(x.DidDocument)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DidResolutionMetadata != nil {
			l = options.Size(x.DidResolutionMetadata)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DidDocumentMetadata != nil {
			l = options.Size(x.DidDocumentMetadata)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ResolveDidRequestResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.DidDocumentMetadata != nil {
			encoded, err := options.Marshal(x.DidDocumentMetadata)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x1a
		}
		if x.DidResolutionMetadata != nil {
			encoded, err := options.Marshal(x.DidResolutionMetadata)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if x.DidDocument != nil {
			encoded, err := options.Marshal(x.DidDocument)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ResolveDidRequestResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ResolveDidRequestResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ResolveDidRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.DidDocument == nil {
					x.DidDocument = &DIDDocument{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.DidDocument); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DidResolutionMetadata", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.DidResolutionMetadata == nil {
					x.DidResolutionMetadata = &DidResolutionMetadata{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.DidResolutionMetadata); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DidDocumentMetadata", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.DidDocumentMetadata == nil {
					x.DidDocumentMetadata = &DidDocumentMetadata{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.DidDocumentMetadata); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: smplidentitychain/did/resolve_did_request_response.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveDidRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DidDocument           *DIDDocument           `protobuf:"bytes,1,opt,name=didDocument,proto3" json:"didDocument,omitempty"`
	DidResolutionMetadata *DidResolutionMetadata `protobuf:"bytes,2,opt,name=didResolutionMetadata,proto3" json:"didResolutionMetadata,omitempty"`
	DidDocumentMetadata   *DidDocumentMetadata   `protobuf:"bytes,3,opt,name=didDocumentMetadata,proto3" json:"didDocumentMetadata,omitempty"`
}

func (x *ResolveDidRequestResponse) Reset() {
	*x = ResolveDidRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smplidentitychain_did_resolve_did_request_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveDidRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDidRequestResponse) ProtoMessage() {}

// Deprecated: Use ResolveDidRequestResponse.ProtoReflect.Descriptor instead.
func (*ResolveDidRequestResponse) Descriptor() ([]byte, []int) {
	return file_smplidentitychain_did_resolve_did_request_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveDidRequestResponse) GetDidDocument() *DIDDocument {
	if x != nil {
		return x.DidDocument
	}
	return nil
}

func (x *ResolveDidRequestResponse) GetDidResolutionMetadata() *DidResolutionMetadata {
	if x != nil {
		return x.DidResolutionMetadata
	}
	return nil
}

func (x *ResolveDidRequestResponse) GetDidDocumentMetadata() *DidDocumentMetadata {
	if x != nil {
		return x.DidDocumentMetadata
	}
	return nil
}

var File_smplidentitychain_did_resolve_did_request_response_proto protoreflect.FileDescriptor

var file_smplidentitychain_did_resolve_did_request_response_proto_rawDesc = []byte{
	0x0a, 0x38, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x5f,
	0x64, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x6d, 0x70, 0x6c,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69,
	0x64, 0x1a, 0x28, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x64, 0x69, 0x64, 0x5f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x73, 0x6d, 0x70,
	0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64,
	0x69, 0x64, 0x2f, 0x64, 0x69, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x33,
	0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x64, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x0b, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x44,
	0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x64, 0x69, 0x64, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x15, 0x64, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x44,
	0x69, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x15, 0x64, 0x69, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x5c, 0x0a, 0x13, 0x64,
	0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64,
	0x2e, 0x44, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x13, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0xd8, 0x01, 0x0a, 0x19, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x42, 0x1e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x44, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6d, 0x70, 0x6c,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69,
	0x64, 0xa2, 0x02, 0x03, 0x53, 0x44, 0x58, 0xaa, 0x02, 0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x69, 0x64, 0xca,
	0x02, 0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0xe2, 0x02, 0x21, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x53, 0x6d,
	0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a,
	0x3a, 0x44, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smplidentitychain_did_resolve_did_request_response_proto_rawDescOnce sync.Once
	file_smplidentitychain_did_resolve_did_request_response_proto_rawDescData = file_smplidentitychain_did_resolve_did_request_response_proto_rawDesc
)

func file_smplidentitychain_did_resolve_did_request_response_proto_rawDescGZIP() []byte {
	file_smplidentitychain_did_resolve_did_request_response_proto_rawDescOnce.Do(func() {
		file_smplidentitychain_did_resolve_did_request_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_smplidentitychain_did_resolve_did_request_response_proto_rawDescData)
	})
	return file_smplidentitychain_did_resolve_did_request_response_proto_rawDescData
}

var file_smplidentitychain_did_resolve_did_request_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smplidentitychain_did_resolve_did_request_response_proto_goTypes = []interface{}{
	(*ResolveDidRequestResponse)(nil), // 0: smplidentitychain.did.ResolveDidRequestResponse
	(*DIDDocument)(nil),               // 1: smplidentitychain.did.DIDDocument
	(*DidResolutionMetadata)(nil),     // 2: smplidentitychain.did.DidResolutionMetadata
	(*DidDocumentMetadata)(nil),       // 3: smplidentitychain.did.DidDocumentMetadata
}
var file_smplidentitychain_did_resolve_did_request_response_proto_depIdxs = []int32{
	1, // 0: smplidentitychain.did.ResolveDidRequestResponse.didDocument:type_name -> smplidentitychain.did.DIDDocument
	2, // 1: smplidentitychain.did.ResolveDidRequestResponse.didResolutionMetadata:type_name -> smplidentitychain.did.DidResolutionMetadata
	3, // 2: smplidentitychain.did.ResolveDidRequestResponse.didDocumentMetadata:type_name -> smplidentitychain.did.DidDocumentMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_smplidentitychain_did_resolve_did_request_response_proto_init() }
func file_smplidentitychain_did_resolve_did_request_response_proto_init() {
	if File_smplidentitychain_did_resolve_did_request_response_proto != nil {
		return
	}
	file_smplidentitychain_did_did_document_proto_init()
	file_smplidentitychain_did_did_document_metadata_proto_init()
	file_smplidentitychain_did_did_resolution_metadata_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_smplidentitychain_did_resolve_did_request_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveDidRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smplidentitychain_did_resolve_did_request_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smplidentitychain_did_resolve_did_request_response_proto_goTypes,
		DependencyIndexes: file_smplidentitychain_did_resolve_did_request_response_proto_depIdxs,
		MessageInfos:      file_smplidentitychain_did_resolve_did_request_response_proto_msgTypes,
	}.Build()
	File_smplidentitychain_did_resolve_did_request_response_proto = out.File
	file_smplidentitychain_did_resolve_did_request_response_proto_rawDesc = nil
	file_smplidentitychain_did_resolve_did_request_response_proto_goTypes = nil
	file_smplidentitychain_did_resolve_did_request_response_proto_depIdxs = nil
}
