// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package did

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_VerificationRelationship                        protoreflect.MessageDescriptor
	fd_VerificationRelationship_verification_method_id protoreflect.FieldDescriptor
	fd_VerificationRelationship_verification_method    protoreflect.FieldDescriptor
)

func init() {
	file_smplidentitychain_did_verification_relationship_proto_init()
	md_VerificationRelationship = File_smplidentitychain_did_verification_relationship_proto.Messages().ByName("VerificationRelationship")
	fd_VerificationRelationship_verification_method_id = md_VerificationRelationship.Fields().ByName("verification_method_id")
	fd_VerificationRelationship_verification_method = md_VerificationRelationship.Fields().ByName("verification_method")
}

var _ protoreflect.Message = (*fastReflection_VerificationRelationship)(nil)

type fastReflection_VerificationRelationship VerificationRelationship

func (x *VerificationRelationship) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VerificationRelationship)(x)
}

func (x *VerificationRelationship) slowProtoReflect() protoreflect.Message {
	mi := &file_smplidentitychain_did_verification_relationship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VerificationRelationship_messageType fastReflection_VerificationRelationship_messageType
var _ protoreflect.MessageType = fastReflection_VerificationRelationship_messageType{}

type fastReflection_VerificationRelationship_messageType struct{}

func (x fastReflection_VerificationRelationship_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VerificationRelationship)(nil)
}
func (x fastReflection_VerificationRelationship_messageType) New() protoreflect.Message {
	return new(fastReflection_VerificationRelationship)
}
func (x fastReflection_VerificationRelationship_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VerificationRelationship
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VerificationRelationship) Descriptor() protoreflect.MessageDescriptor {
	return md_VerificationRelationship
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VerificationRelationship) Type() protoreflect.MessageType {
	return _fastReflection_VerificationRelationship_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VerificationRelationship) New() protoreflect.Message {
	return new(fastReflection_VerificationRelationship)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VerificationRelationship) Interface() protoreflect.ProtoMessage {
	return (*VerificationRelationship)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VerificationRelationship) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Content != nil {
		switch o := x.Content.(type) {
		case *VerificationRelationship_VerificationMethodId:
			v := o.VerificationMethodId
			value := protoreflect.ValueOfString(v)
			if !f(fd_VerificationRelationship_verification_method_id, value) {
				return
			}
		case *VerificationRelationship_VerificationMethod:
			v := o.VerificationMethod
			value := protoreflect.ValueOfMessage(v.ProtoReflect())
			if !f(fd_VerificationRelationship_verification_method, value) {
				return
			}
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VerificationRelationship) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		if x.Content == nil {
			return false
		} else if _, ok := x.Content.(*VerificationRelationship_VerificationMethodId); ok {
			return true
		} else {
			return false
		}
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		if x.Content == nil {
			return false
		} else if _, ok := x.Content.(*VerificationRelationship_VerificationMethod); ok {
			return true
		} else {
			return false
		}
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VerificationRelationship) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		x.Content = nil
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		x.Content = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VerificationRelationship) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		if x.Content == nil {
			return protoreflect.ValueOfString("")
		} else if v, ok := x.Content.(*VerificationRelationship_VerificationMethodId); ok {
			return protoreflect.ValueOfString(v.VerificationMethodId)
		} else {
			return protoreflect.ValueOfString("")
		}
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		if x.Content == nil {
			return protoreflect.ValueOfMessage((*VerificationMethod)(nil).ProtoReflect())
		} else if v, ok := x.Content.(*VerificationRelationship_VerificationMethod); ok {
			return protoreflect.ValueOfMessage(v.VerificationMethod.ProtoReflect())
		} else {
			return protoreflect.ValueOfMessage((*VerificationMethod)(nil).ProtoReflect())
		}
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VerificationRelationship) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		cv := value.Interface().(string)
		x.Content = &VerificationRelationship_VerificationMethodId{VerificationMethodId: cv}
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		cv := value.Message().Interface().(*VerificationMethod)
		x.Content = &VerificationRelationship_VerificationMethod{VerificationMethod: cv}
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VerificationRelationship) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		if x.Content == nil {
			value := &VerificationMethod{}
			oneofValue := &VerificationRelationship_VerificationMethod{VerificationMethod: value}
			x.Content = oneofValue
			return protoreflect.ValueOfMessage(value.ProtoReflect())
		}
		switch m := x.Content.(type) {
		case *VerificationRelationship_VerificationMethod:
			return protoreflect.ValueOfMessage(m.VerificationMethod.ProtoReflect())
		default:
			value := &VerificationMethod{}
			oneofValue := &VerificationRelationship_VerificationMethod{VerificationMethod: value}
			x.Content = oneofValue
			return protoreflect.ValueOfMessage(value.ProtoReflect())
		}
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		panic(fmt.Errorf("field verification_method_id of message smplidentitychain.did.VerificationRelationship is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VerificationRelationship) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "smplidentitychain.did.VerificationRelationship.verification_method_id":
		return protoreflect.ValueOfString("")
	case "smplidentitychain.did.VerificationRelationship.verification_method":
		value := &VerificationMethod{}
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: smplidentitychain.did.VerificationRelationship"))
		}
		panic(fmt.Errorf("message smplidentitychain.did.VerificationRelationship does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VerificationRelationship) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	case "smplidentitychain.did.VerificationRelationship.content":
		if x.Content == nil {
			return nil
		}
		switch x.Content.(type) {
		case *VerificationRelationship_VerificationMethodId:
			return x.Descriptor().Fields().ByName("verification_method_id")
		case *VerificationRelationship_VerificationMethod:
			return x.Descriptor().Fields().ByName("verification_method")
		}
	default:
		panic(fmt.Errorf("%s is not a oneof field in smplidentitychain.did.VerificationRelationship", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VerificationRelationship) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VerificationRelationship) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VerificationRelationship) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VerificationRelationship) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VerificationRelationship)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		switch x := x.Content.(type) {
		case *VerificationRelationship_VerificationMethodId:
			if x == nil {
				break
			}
			l = len(x.VerificationMethodId)
			n += 1 + l + runtime.Sov(uint64(l))
		case *VerificationRelationship_VerificationMethod:
			if x == nil {
				break
			}
			l = options.Size(x.VerificationMethod)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VerificationRelationship)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		switch x := x.Content.(type) {
		case *VerificationRelationship_VerificationMethodId:
			i -= len(x.VerificationMethodId)
			copy(dAtA[i:], x.VerificationMethodId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VerificationMethodId)))
			i--
			dAtA[i] = 0xa
		case *VerificationRelationship_VerificationMethod:
			encoded, err := options.Marshal(x.VerificationMethod)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VerificationRelationship)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VerificationRelationship: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VerificationRelationship: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VerificationMethodId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Content = &VerificationRelationship_VerificationMethodId{string(dAtA[iNdEx:postIndex])}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VerificationMethod", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				v := &VerificationMethod{}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], v); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				x.Content = &VerificationRelationship_VerificationMethod{v}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: smplidentitychain/did/verification_relationship.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationRelationship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*VerificationRelationship_VerificationMethodId
	//	*VerificationRelationship_VerificationMethod
	Content isVerificationRelationship_Content `protobuf_oneof:"content"`
}

func (x *VerificationRelationship) Reset() {
	*x = VerificationRelationship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smplidentitychain_did_verification_relationship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRelationship) ProtoMessage() {}

// Deprecated: Use VerificationRelationship.ProtoReflect.Descriptor instead.
func (*VerificationRelationship) Descriptor() ([]byte, []int) {
	return file_smplidentitychain_did_verification_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationRelationship) GetContent() isVerificationRelationship_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VerificationRelationship) GetVerificationMethodId() string {
	if x, ok := x.GetContent().(*VerificationRelationship_VerificationMethodId); ok {
		return x.VerificationMethodId
	}
	return ""
}

func (x *VerificationRelationship) GetVerificationMethod() *VerificationMethod {
	if x, ok := x.GetContent().(*VerificationRelationship_VerificationMethod); ok {
		return x.VerificationMethod
	}
	return nil
}

type isVerificationRelationship_Content interface {
	isVerificationRelationship_Content()
}

type VerificationRelationship_VerificationMethodId struct {
	VerificationMethodId string `protobuf:"bytes,1,opt,name=verification_method_id,json=verificationMethodId,proto3,oneof"`
}

type VerificationRelationship_VerificationMethod struct {
	VerificationMethod *VerificationMethod `protobuf:"bytes,2,opt,name=verification_method,json=verificationMethod,proto3,oneof"`
}

func (*VerificationRelationship_VerificationMethodId) isVerificationRelationship_Content() {}

func (*VerificationRelationship_VerificationMethod) isVerificationRelationship_Content() {}

var File_smplidentitychain_did_verification_relationship_proto protoreflect.FileDescriptor

var file_smplidentitychain_did_verification_relationship_proto_rawDesc = []byte{
	0x0a, 0x35, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x1a, 0x2f,
	0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x64, 0x69, 0x64, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbb, 0x01, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x12, 0x36, 0x0a, 0x16,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x14,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x49, 0x64, 0x12, 0x5c, 0x0a, 0x13, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x00, 0x52, 0x12,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0xd7, 0x01,
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x69, 0x64, 0x42, 0x1d, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x64, 0x69, 0x64, 0xa2, 0x02, 0x03, 0x53, 0x44, 0x58, 0xaa, 0x02, 0x15, 0x53, 0x6d, 0x70,
	0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x44,
	0x69, 0x64, 0xca, 0x02, 0x15, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x44, 0x69, 0x64, 0xe2, 0x02, 0x21, 0x53, 0x6d, 0x70,
	0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x44,
	0x69, 0x64, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x16, 0x53, 0x6d, 0x70, 0x6c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x3a, 0x3a, 0x44, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smplidentitychain_did_verification_relationship_proto_rawDescOnce sync.Once
	file_smplidentitychain_did_verification_relationship_proto_rawDescData = file_smplidentitychain_did_verification_relationship_proto_rawDesc
)

func file_smplidentitychain_did_verification_relationship_proto_rawDescGZIP() []byte {
	file_smplidentitychain_did_verification_relationship_proto_rawDescOnce.Do(func() {
		file_smplidentitychain_did_verification_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(file_smplidentitychain_did_verification_relationship_proto_rawDescData)
	})
	return file_smplidentitychain_did_verification_relationship_proto_rawDescData
}

var file_smplidentitychain_did_verification_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smplidentitychain_did_verification_relationship_proto_goTypes = []interface{}{
	(*VerificationRelationship)(nil), // 0: smplidentitychain.did.VerificationRelationship
	(*VerificationMethod)(nil),       // 1: smplidentitychain.did.VerificationMethod
}
var file_smplidentitychain_did_verification_relationship_proto_depIdxs = []int32{
	1, // 0: smplidentitychain.did.VerificationRelationship.verification_method:type_name -> smplidentitychain.did.VerificationMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_smplidentitychain_did_verification_relationship_proto_init() }
func file_smplidentitychain_did_verification_relationship_proto_init() {
	if File_smplidentitychain_did_verification_relationship_proto != nil {
		return
	}
	file_smplidentitychain_did_verification_method_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_smplidentitychain_did_verification_relationship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationRelationship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_smplidentitychain_did_verification_relationship_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*VerificationRelationship_VerificationMethodId)(nil),
		(*VerificationRelationship_VerificationMethod)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smplidentitychain_did_verification_relationship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smplidentitychain_did_verification_relationship_proto_goTypes,
		DependencyIndexes: file_smplidentitychain_did_verification_relationship_proto_depIdxs,
		MessageInfos:      file_smplidentitychain_did_verification_relationship_proto_msgTypes,
	}.Build()
	File_smplidentitychain_did_verification_relationship_proto = out.File
	file_smplidentitychain_did_verification_relationship_proto_rawDesc = nil
	file_smplidentitychain_did_verification_relationship_proto_goTypes = nil
	file_smplidentitychain_did_verification_relationship_proto_depIdxs = nil
}
