// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smplidentitychain/did/did_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DidInfo struct {
	DidDocument         *DIDDocument         `protobuf:"bytes,1,opt,name=didDocument,proto3" json:"didDocument,omitempty"`
	DidDocumentMetadata *DidDocumentMetadata `protobuf:"bytes,2,opt,name=didDocumentMetadata,proto3" json:"didDocumentMetadata,omitempty"`
}

func (m *DidInfo) Reset()         { *m = DidInfo{} }
func (m *DidInfo) String() string { return proto.CompactTextString(m) }
func (*DidInfo) ProtoMessage()    {}
func (*DidInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_528beecfbfe743f0, []int{0}
}
func (m *DidInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DidInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DidInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DidInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DidInfo.Merge(m, src)
}
func (m *DidInfo) XXX_Size() int {
	return m.Size()
}
func (m *DidInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DidInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DidInfo proto.InternalMessageInfo

func (m *DidInfo) GetDidDocument() *DIDDocument {
	if m != nil {
		return m.DidDocument
	}
	return nil
}

func (m *DidInfo) GetDidDocumentMetadata() *DidDocumentMetadata {
	if m != nil {
		return m.DidDocumentMetadata
	}
	return nil
}

func init() {
	proto.RegisterType((*DidInfo)(nil), "smplidentitychain.did.DidInfo")
}

func init() {
	proto.RegisterFile("smplidentitychain/did/did_info.proto", fileDescriptor_528beecfbfe743f0)
}

var fileDescriptor_528beecfbfe743f0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0xce, 0x2d, 0xc8,
	0xc9, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xc9,
	0x4c, 0x01, 0xe1, 0xf8, 0xcc, 0xbc, 0xb4, 0x7c, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x51,
	0x0c, 0x55, 0x7a, 0x29, 0x99, 0x29, 0x52, 0x1a, 0xb8, 0x35, 0xa7, 0xe4, 0x27, 0x97, 0xe6, 0xa6,
	0xe6, 0x95, 0x40, 0x0c, 0x90, 0x32, 0x24, 0xac, 0x32, 0x3e, 0x37, 0xb5, 0x24, 0x31, 0x25, 0xb1,
	0x24, 0x11, 0xa2, 0x45, 0x69, 0x2d, 0x23, 0x17, 0xbb, 0x4b, 0x66, 0x8a, 0x67, 0x5e, 0x5a, 0xbe,
	0x90, 0x0b, 0x17, 0x77, 0x4a, 0x66, 0x8a, 0x0b, 0x54, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7,
	0x91, 0x92, 0x1e, 0x56, 0x57, 0xe9, 0xb9, 0x78, 0xba, 0xc0, 0x54, 0x06, 0x21, 0x6b, 0x13, 0x8a,
	0xe1, 0x12, 0x46, 0xe2, 0xfa, 0x42, 0xad, 0x93, 0x60, 0x02, 0x9b, 0xa6, 0x85, 0xcb, 0x34, 0x4c,
	0x1d, 0x41, 0xd8, 0x8c, 0x71, 0x0a, 0x3a, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07,
	0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86,
	0x00, 0xc6, 0x28, 0xb3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe0,
	0xdc, 0x82, 0x1c, 0xd7, 0xe4, 0xfc, 0xe2, 0xca, 0xe2, 0x92, 0x54, 0x08, 0xcf, 0x13, 0x6a, 0xa9,
	0x33, 0x38, 0x5c, 0x2a, 0xc0, 0x21, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x0e, 0x0a,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xfb, 0x4f, 0x9f, 0xa6, 0x01, 0x00, 0x00,
}

func (m *DidInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DidInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DidInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DidDocumentMetadata != nil {
		{
			size, err := m.DidDocumentMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDidInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.DidDocument != nil {
		{
			size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDidInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDidInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovDidInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DidInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DidDocument != nil {
		l = m.DidDocument.Size()
		n += 1 + l + sovDidInfo(uint64(l))
	}
	if m.DidDocumentMetadata != nil {
		l = m.DidDocumentMetadata.Size()
		n += 1 + l + sovDidInfo(uint64(l))
	}
	return n
}

func sovDidInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDidInfo(x uint64) (n int) {
	return sovDidInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DidInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDidInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DidInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DidInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidDocument == nil {
				m.DidDocument = &DIDDocument{}
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocumentMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidDocumentMetadata == nil {
				m.DidDocumentMetadata = &DidDocumentMetadata{}
			}
			if err := m.DidDocumentMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDidInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDidInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDidInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDidInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDidInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDidInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDidInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDidInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDidInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDidInfo = fmt.Errorf("proto: unexpected end of group")
)
