// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smplidentitychain/did/did_document.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DIDDocument struct {
	Contexts              []string                    `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	Id                    string                      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	VerificationMethods   []*VerificationMethod       `protobuf:"bytes,3,rep,name=verification_methods,json=verificationMethod,proto3" json:"verification_methods,omitempty"`
	Authentications       []*VerificationRelationship `protobuf:"bytes,4,rep,name=authentications,json=authentication,proto3" json:"authentications,omitempty"`
	AssertionMethods      []*VerificationRelationship `protobuf:"bytes,5,rep,name=assertion_methods,json=assertionMethod,proto3" json:"assertion_methods,omitempty"`
	KeyAgreements         []*VerificationRelationship `protobuf:"bytes,6,rep,name=key_agreements,json=keyAgreement,proto3" json:"key_agreements,omitempty"`
	CapabilityInvocations []*VerificationRelationship `protobuf:"bytes,7,rep,name=capability_invocations,json=capabilityInvocation,proto3" json:"capability_invocations,omitempty"`
	CapabilityDelegations []*VerificationRelationship `protobuf:"bytes,8,rep,name=capability_delegations,json=capabilityDelegation,proto3" json:"capability_delegations,omitempty"`
	Services              []*Service                  `protobuf:"bytes,9,rep,name=services,json=service,proto3" json:"services,omitempty"`
}

func (m *DIDDocument) Reset()         { *m = DIDDocument{} }
func (m *DIDDocument) String() string { return proto.CompactTextString(m) }
func (*DIDDocument) ProtoMessage()    {}
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_93dd9bf00216960a, []int{0}
}
func (m *DIDDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DIDDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DIDDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DIDDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DIDDocument.Merge(m, src)
}
func (m *DIDDocument) XXX_Size() int {
	return m.Size()
}
func (m *DIDDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_DIDDocument.DiscardUnknown(m)
}

var xxx_messageInfo_DIDDocument proto.InternalMessageInfo

func (m *DIDDocument) GetContexts() []string {
	if m != nil {
		return m.Contexts
	}
	return nil
}

func (m *DIDDocument) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DIDDocument) GetVerificationMethods() []*VerificationMethod {
	if m != nil {
		return m.VerificationMethods
	}
	return nil
}

func (m *DIDDocument) GetAuthentications() []*VerificationRelationship {
	if m != nil {
		return m.Authentications
	}
	return nil
}

func (m *DIDDocument) GetAssertionMethods() []*VerificationRelationship {
	if m != nil {
		return m.AssertionMethods
	}
	return nil
}

func (m *DIDDocument) GetKeyAgreements() []*VerificationRelationship {
	if m != nil {
		return m.KeyAgreements
	}
	return nil
}

func (m *DIDDocument) GetCapabilityInvocations() []*VerificationRelationship {
	if m != nil {
		return m.CapabilityInvocations
	}
	return nil
}

func (m *DIDDocument) GetCapabilityDelegations() []*VerificationRelationship {
	if m != nil {
		return m.CapabilityDelegations
	}
	return nil
}

func (m *DIDDocument) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*DIDDocument)(nil), "smplidentitychain.did.DIDDocument")
}

func init() {
	proto.RegisterFile("smplidentitychain/did/did_document.proto", fileDescriptor_93dd9bf00216960a)
}

var fileDescriptor_93dd9bf00216960a = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x9b, 0xd6, 0x7b, 0x6f, 0x3b, 0x57, 0x7a, 0x71, 0xa8, 0x12, 0xba, 0x08, 0x45, 0x37,
	0x71, 0x93, 0x80, 0xa2, 0xe0, 0x52, 0x8d, 0x8b, 0x2e, 0x04, 0x49, 0x51, 0xc4, 0x2e, 0x42, 0x3a,
	0x73, 0x6c, 0x0e, 0x4d, 0x32, 0x21, 0x33, 0x0d, 0xcd, 0x5b, 0xf8, 0x22, 0xbe, 0x87, 0xcb, 0x2e,
	0x5d, 0x4a, 0xfb, 0x22, 0xd2, 0x24, 0x8d, 0xad, 0x8d, 0x50, 0xea, 0x22, 0x90, 0x19, 0xfe, 0xff,
	0x3b, 0xff, 0x39, 0xcc, 0x21, 0xa6, 0x8c, 0x92, 0x10, 0x39, 0xc4, 0x0a, 0x55, 0xce, 0x02, 0x1f,
	0x63, 0x9b, 0x23, 0xdf, 0x7d, 0x1e, 0x17, 0x6c, 0x19, 0x41, 0xac, 0xac, 0x24, 0x15, 0x4a, 0xd0,
	0x87, 0x27, 0x4a, 0x8b, 0x23, 0x1f, 0x3e, 0x69, 0x06, 0x48, 0x48, 0x33, 0x64, 0x50, 0x7a, 0x87,
	0x76, 0xb3, 0x28, 0x83, 0x14, 0xbf, 0x22, 0xf3, 0x15, 0x8a, 0xd8, 0x8b, 0x40, 0x05, 0x82, 0x57,
	0x86, 0x17, 0x67, 0x18, 0x52, 0x08, 0x8b, 0x1f, 0x19, 0x60, 0x52, 0xda, 0x1e, 0x7f, 0xbf, 0x22,
	0xb7, 0xce, 0xd8, 0x71, 0xaa, 0xe4, 0x74, 0x48, 0xba, 0x4c, 0xc4, 0x0a, 0x56, 0x4a, 0xea, 0xda,
	0xa8, 0x63, 0xf6, 0xdc, 0xfa, 0x4c, 0xfb, 0xa4, 0x8d, 0x5c, 0x6f, 0x8f, 0x34, 0xb3, 0xe7, 0xb6,
	0x91, 0xd3, 0x29, 0x19, 0x34, 0xe4, 0x91, 0x7a, 0x67, 0xd4, 0x31, 0x6f, 0x9f, 0x3d, 0xb5, 0x1a,
	0xdb, 0xb7, 0x3e, 0x1d, 0x58, 0xde, 0x17, 0x0e, 0x97, 0x66, 0x27, 0x77, 0xf4, 0x33, 0xb9, 0xf3,
	0x97, 0x2a, 0xd8, 0xb9, 0xcb, 0x7b, 0xa9, 0xdf, 0x2b, 0xb8, 0xf6, 0x19, 0x5c, 0xf7, 0xa0, 0x51,
	0xb7, 0x7f, 0xcc, 0xa1, 0x53, 0xf2, 0xc0, 0x97, 0x12, 0xd2, 0xa3, 0xcc, 0x57, 0x97, 0xb1, 0xef,
	0x6a, 0x52, 0x15, 0xfb, 0x23, 0xe9, 0x2f, 0x20, 0xf7, 0xfc, 0x79, 0x0a, 0xb0, 0x1b, 0xa8, 0xd4,
	0xaf, 0x2f, 0x23, 0xdf, 0x5f, 0x40, 0xfe, 0x7a, 0x4f, 0xa1, 0x40, 0x1e, 0x31, 0x3f, 0xf1, 0x67,
	0x18, 0xa2, 0xca, 0x3d, 0x8c, 0x33, 0xb1, 0x1f, 0xca, 0xcd, 0x65, 0xf8, 0xc1, 0x1f, 0xdc, 0xb8,
	0xa6, 0xfd, 0x55, 0x86, 0x43, 0x08, 0xf3, 0xaa, 0x4c, 0xf7, 0xbf, 0xcb, 0x38, 0x35, 0x8d, 0xbe,
	0x22, 0xdd, 0xea, 0xb5, 0x4b, 0xbd, 0x57, 0x80, 0x8d, 0x7f, 0x80, 0x27, 0xa5, 0xcc, 0xbd, 0xa9,
	0xf4, 0x6f, 0xdc, 0x1f, 0x1b, 0x43, 0x5b, 0x6f, 0x0c, 0xed, 0xd7, 0xc6, 0xd0, 0xbe, 0x6d, 0x8d,
	0xd6, 0x7a, 0x6b, 0xb4, 0x7e, 0x6e, 0x8d, 0xd6, 0x07, 0xed, 0xcb, 0xcb, 0x39, 0xaa, 0x60, 0x39,
	0xb3, 0x98, 0x88, 0xec, 0x49, 0x94, 0x84, 0xef, 0x98, 0x90, 0xb9, 0x54, 0x50, 0x9e, 0xc6, 0x15,
	0xfc, 0x6d, 0xb1, 0x1b, 0xab, 0x62, 0x3b, 0x54, 0x9e, 0x80, 0x9c, 0x5d, 0x17, 0xab, 0xf0, 0xfc,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x0d, 0x9f, 0x87, 0xda, 0x03, 0x00, 0x00,
}

func (m *DIDDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DIDDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DIDDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Services) > 0 {
		for iNdEx := len(m.Services) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Services[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.CapabilityDelegations) > 0 {
		for iNdEx := len(m.CapabilityDelegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CapabilityDelegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.CapabilityInvocations) > 0 {
		for iNdEx := len(m.CapabilityInvocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CapabilityInvocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.KeyAgreements) > 0 {
		for iNdEx := len(m.KeyAgreements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeyAgreements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AssertionMethods) > 0 {
		for iNdEx := len(m.AssertionMethods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssertionMethods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Authentications) > 0 {
		for iNdEx := len(m.Authentications) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Authentications[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.VerificationMethods) > 0 {
		for iNdEx := len(m.VerificationMethods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VerificationMethods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDidDocument(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Contexts) > 0 {
		for iNdEx := len(m.Contexts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Contexts[iNdEx])
			copy(dAtA[i:], m.Contexts[iNdEx])
			i = encodeVarintDidDocument(dAtA, i, uint64(len(m.Contexts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintDidDocument(dAtA []byte, offset int, v uint64) int {
	offset -= sovDidDocument(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DIDDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Contexts) > 0 {
		for _, s := range m.Contexts {
			l = len(s)
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDidDocument(uint64(l))
	}
	if len(m.VerificationMethods) > 0 {
		for _, e := range m.VerificationMethods {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.Authentications) > 0 {
		for _, e := range m.Authentications {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.AssertionMethods) > 0 {
		for _, e := range m.AssertionMethods {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.KeyAgreements) > 0 {
		for _, e := range m.KeyAgreements {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.CapabilityInvocations) > 0 {
		for _, e := range m.CapabilityInvocations {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.CapabilityDelegations) > 0 {
		for _, e := range m.CapabilityDelegations {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.Services) > 0 {
		for _, e := range m.Services {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	return n
}

func sovDidDocument(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDidDocument(x uint64) (n int) {
	return sovDidDocument(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DIDDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDidDocument
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DIDDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contexts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contexts = append(m.Contexts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationMethods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationMethods = append(m.VerificationMethods, &VerificationMethod{})
			if err := m.VerificationMethods[len(m.VerificationMethods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authentications", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authentications = append(m.Authentications, &VerificationRelationship{})
			if err := m.Authentications[len(m.Authentications)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssertionMethods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssertionMethods = append(m.AssertionMethods, &VerificationRelationship{})
			if err := m.AssertionMethods[len(m.AssertionMethods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyAgreements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyAgreements = append(m.KeyAgreements, &VerificationRelationship{})
			if err := m.KeyAgreements[len(m.KeyAgreements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityInvocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapabilityInvocations = append(m.CapabilityInvocations, &VerificationRelationship{})
			if err := m.CapabilityInvocations[len(m.CapabilityInvocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityDelegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapabilityDelegations = append(m.CapabilityDelegations, &VerificationRelationship{})
			if err := m.CapabilityDelegations[len(m.CapabilityDelegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Services", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Services = append(m.Services, &Service{})
			if err := m.Services[len(m.Services)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDidDocument(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDidDocument
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDidDocument(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDidDocument
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDidDocument
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDidDocument
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDidDocument
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDidDocument        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDidDocument          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDidDocument = fmt.Errorf("proto: unexpected end of group")
)
